blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Our companie Website
    url: https://rmr-inc.dynamored.com
    about: All our work
  - name: ğŸ“‘ Project Subject
    url: https://cdn.dynamored.com/resources/esgi/2021_22/pa/Sujet.pdf
    about: Description given of the project to be carried out 